# Generated by Django 5.1.7 on 2025-03-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('assessment_form', models.CharField(choices=[('Экзамен', 'Экзамен'), ('Зачет', 'Зачет')], max_length=10, verbose_name='Форма оценивания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('post', models.CharField(choices=[('Ассистент', 'Ассистент'), ('Преподаватель', 'Преподаватель'), ('Старший преподаватель', 'Старший преподаватель'), ('Доцент', 'Доцент'), ('Профессор', 'Профессор'), ('Заведующий кафедрой', 'Заведующий кафедрой'), ('Декан', 'Декан')], max_length=30, verbose_name='Должность')),
                ('role', models.CharField(default='Преподаватель', max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кафедра')),
                ('faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.faculties', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер специальности')),
                ('name', models.CharField(max_length=100, verbose_name='Специальность')),
                ('form_of_education', models.CharField(choices=[('Очная', 'Очная'), ('Заочная', 'Заочная'), ('Очно-заочная', 'Очно-заочная')], max_length=15, verbose_name='Форма обучения')),
                ('period_of_study', models.CharField(choices=[('3 года 10 месяцев', '3 года 10 месяцев'), ('4 года 10 месяцев', '4 года 10 месяцев')], max_length=50, verbose_name='Срок обучения')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.departments', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('year_of_admission', models.IntegerField(verbose_name='Год поступления')),
                ('specialty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.specialties', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(default='Студент', max_length=20, verbose_name='Роль')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_exam', models.CharField(blank=True, choices=[('неудовлетворительно', 'неудовлетворительно'), ('удовлетворительно', 'удовлетворительно'), ('хорошо', 'хорошо'), ('отлично', 'отлично')], max_length=20, verbose_name='Оценка за экзамен')),
                ('grade_test', models.CharField(blank=True, choices=[('не зачтено', 'не зачтено'), ('зачтено', 'зачтено')], max_length=10, verbose_name='Оценка за зачет')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.students', verbose_name='Студент')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='Номер семестра')),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.groups', verbose_name='Группа')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subjects', verbose_name='Предмет')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебный план',
            },
        ),
    ]
