# Generated by Django 5.1.7 on 2025-03-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_students_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='role',
            field=models.CharField(default='Студент', editable=False, max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='role',
            field=models.CharField(default='Преподаватель', editable=False, max_length=20, verbose_name='Роль'),
        ),
    ]
