# Generated by Django 5.1.7 on 2025-03-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_teachers_user_id_alter_students_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
